### ISSUE TITLE
Background is completely transparent when used on desktop

### ISSUE THREAD

**Issue by Electw** [k-donn/plasmoid-wunderground#15]
Hello, great widget. However, the background for the widget is transparent when used on the desktop, which makes it very hard to read.

![image](https://user-images.githubusercontent.com/55963122/116765215-f7c75d00-a9d8-11eb-89b0-6a21fde36848.png)

**Comment by k-donn** [comment]
Oh, don't worry, if you `right-click` on the widget or desktop and `Enter Edit Mode` or whatever your version of KDE calls editing widgets, hover over the widget and click the `a` button that is below the rotate and configure option and it will let you change the background.

**Comment by Electw** [comment]
I didn't know you could do that with some Plasma widgets. Thank you for your help!
