### ISSUE TITLE
Incorrect meteocon in certain circumstances

### ISSUE THREAD

**Issue by Ccjr0** [k-donn/plasmoid-wunderground#18]
Ah, yes. Scattered snowstorms in the middle of June.

![Screenshot_20210625_220858](https://user-images.githubusercontent.com/71677470/123500701-89cc9a00-d605-11eb-9209-332ea6a87904.png)

**Comment by k-donn** [comment]
Hah lol. I had put the wrong icon for condition 47 (night Sct T-Storms). cf112be160e84764dfee1f93cdfa35a09d895f fixes this.
