### ISSUE TITLE
Station not found or station not active

### ISSUE THREAD

**Issue by ghost** [k-donn/plasmoid-wunderground#28]
Will not pull data from any stations near me. Have tried 6 different ones.
Screenshot
https://pasteboard.co/5aTd4kmmpANC.png

System Info

Operating System: KDE neon 5.23
KDE Plasma Version: 5.23.3
KDE Frameworks Version: 5.87.0
Qt Version: 5.15.3
Kernel Version: 5.11.0-40-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-9300H CPU @ 2.40GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 2060/PCIe/SSE2

**Comment by gnemonix** [comment]
For some reason the API only works for Personal Weather Stations. Official stations (ie. at airports) will not fetch data.

I tested KALMONTG100 and it worked for me.

Any station ID that starts with KAL should work just fine (for your area). If you are not getting any data, the API server may be down or rate limited, or just that specific station is not reporting at the moment. Either try another station, or give it a little while.

![kalmontg100](https://user-images.githubusercontent.com/2272892/142086763-020afaa2-bad2-44e4-a0be-4c98a6a1278b.png)

**Comment by k-donn** [comment]
Hello, thanks for leaving an issue.

This widget does only work with personal weather stations. [All of the "Personal Weather Station" API endpoints here.](https://weather.com/swagger-docs/call-for-code) An airport station falls under different endpoints.

Sorry that there do not appear to be any personal weather stations near the airport you choose. I am in the process of developing a [Plasma Ion](https://techbase.kde.org/Projects/Plasma/Weather/Ions) which would allow for you to input other weather data sources such as the airport for this widget.

Thank you for your interest in the widget!

**Comment by k-donn** [comment]
You can search for personal weather stations around this airport [Here](https://www.wunderground.com/wundermap?renderer=2&Units=english&zoom=11&lat=32.38&lon=-86.35&covid19=0&wxstn=1&wxstnmode=tw&aq=0&aqvalue=0&radar=1&radarType=NaN&radaropa=0.7&satellite=0&satelliteopa=0.8&storm-cells=0&severe=0&severeopa=0.9&sst=0&sstopa=0.8&sstanom=0&sstanomopa=0.8&fronts=0&hur=0&models=0&modelsmodel=ecmwf&modelsopa=0.8&modelstype=SURPRE&lightning=0&fire=0&fireopa=0.9&firePerimeter=0&firePerimeterOpacity=0.9&smoke=0&smokeOpacity=0.9&rep=0&surge=0&tor=0&windstr=0&windstrDensity=undefined&windstreamSpeed=undefined&windstreamSpeedFilter=undefined&windstreamPalette=undefined&hurrArch=0&hurrArchBasin=undefined&hurrArchYear=undefined&hurrArchStorm=undefined) with each of the dots being a station. You can click on them, get the station name, and put it into the widget.
