### ISSUE TITLE
Text is not scaled to fit inside widget boundaries

### ISSUE THREAD

**Issue by picorealm** [k-donn/plasmoid-wunderground#29]
**Describe the bug**
The text of the widget is too large to fit inside the boundaries of the widget and is unreadable.

**To Reproduce**
For Compact Representation Font is set to Default, Font size is set to 28.  For Full Representation Property Header Text Size is set to 16, Property Text Size 12, Temperature Text Size 18.  Am using a High DPI 3840x2160 43" display with KDE Plasma display scaling set to 168.75%.

**Screenshots**
See attached

**Desktop (output of `plasmashell --version && kf5-config --version`):**
plasmashell 5.23.3
Qt: 5.15.2
KDE Frameworks: 5.88.0
kf5-config: 1.0

![plasma-wunderground widget issue](https://user-images.githubusercontent.com/41875886/144100163-e6b9d76c-86c2-4348-8d1d-6392496da288.jpg)

**Comment by rocketfuelindustries** [comment]
Same issue

Compact: Default, 50
Full: 16, 12, 20.
Am using a High DPI 3840x2160, KDE Plasma display scaling set to 100%.

**Desktop (output of plasmashell --version && kf5-config --version):**
plasmashell 5.23.5
Qt: 5.15.2
KDE Frameworks: 5.90.0
kf5-config: 1.0
![Screenshot_20220121_142958](https://user-images.githubusercontent.com/9666815/150466532-8e12bed6-9530-4247-a53b-803742e5c36d.png)

**Comment by k-donn** [comment]
Thank you for using my widget and creating this issue!

I will adjust the calculation for the various rendering sizes to account for high dpi devices.

Thank you again for understanding my busy schedule and any delays!

**Comment by joickle** [comment]
As a temporary fix, changing lines 60 and 61 in `~/.local/share/plasma/plasmoids/com.github.k-donn.plasmoid-wunderground/contents/main.qml` fixed it for me on a 4k display with 144 dpi:
```
Layout.preferredWidth: 900
Layout.preferredHeight: 500
```

**Comment by k-donn** [comment]
Hello, just wanted to touch base to say that I have not forgotten about this. I recently figured out how to test high-dpi mode on my non-high-dpi screen. Upcoming changes to fix this!

**Comment by abrouwers** [comment]
Thanks for posting this, I couldn't figure out how to get everything to fit.
Hopefully the fix is still incoming!

**Comment by k-donn** [comment]
Going forward, I think the best thing is just to make the full representation size configurable in settings.

Doing some testing, it has the same problem as #27 with the size not working after session restarts and first loading.

I'll push out some changes onto `release` with a possible change.

Cloning this repo and installing the plasmoid from the `release` branch will let everyone test how it goes on high DPI screens. It can be installed from the repo with [kpackagetool5](https://community.kde.org/Plasma/DeveloperGuide#Install_the_App).

Thanks for reporting back!
