### ISSUE TITLE
refresh period

### ISSUE THREAD

**Issue by clumsyfingers** [k-donn/plasmoid-wunderground#36]
hi
im confused about the refresh period in the settings, is it really supposed to be refreshed every 15 seconds? and i cant go above 99. id like it to refresh every 30 minutes or something

**Comment by k-donn** [comment]
Hello!

One of the big parts of Wunderground PWS is that each of the stations refresh rapidly so that was the intention for the rapid redfresh. However, I will look into making sure that the refresh period confit field can be set to higher times. 

Thanks!
