### ISSUE TITLE
Wunderground API call fails with provided API key

### ISSUE THREAD

**Issue by jimtuttle** [k-donn/plasmoid-wunderground#37]
**Describe the bug**
Any call to Wunderground API fails with error "Request failed: Access Denied Access Denied You don't have permission to access "httpapiweathercomv2pwsobservationscurrent" on this server."

**To Reproduce**
I've tried several stations over the past 2 days with no change.  Also, I'm not able to generate a personal API key as Wunderground in API KEYS section of my profile says "No API key. You must own a Personal Weather Station in order to generate an API key."

**Screenshots**
[https://imgur.com/a/o5XOV7x](https://imgur.com/a/o5XOV7x)

**Desktop (output of `plasmashell --version && kf5-config --version`):**
plasmashell 5.25.5
Qt: 5.15.4
KDE Frameworks: 5.98.0
kf5-config: 1.0

**Comment by jimtuttle** [comment]
I see another Wundeground plugin is experiencing the same issue so it seems likely that this is change in policy at Wunderground.  See [https://store.kde.org/p/1756638](https://store.kde.org/p/1756638).

**Comment by k-donn** [comment]
Something has changed with what IBM/Wunderground is giving out with the API. I'm looking into seeing how to get this working again. 

Thanks for using my widget!

**Comment by vmisev** [comment]
same error here: ""Error: Request failed: Access Denied ... " ; 
Wunderground 2.4.0, 
plasmashell 5.24.6
Qt: 5.15.5
KDE Frameworks: 5.99.0
FreeBSD 13.1-STABLE

**Comment by lucknaumann** [comment]
Yup.

- **Wunderground**: 2.3.3
- **OS**: KDE neon User 5.26
- **KDE Plasma Version**: 5.26.0
- **KDE Frameworks Version**: 5.99.0
- **Qt Version**: 5.15.6

**Comment by gldickens3** [comment]
I am seeing the same problem.
- Wunderground 2.4.0
- OS: Kubuntu 22.04
- KDE Plasma Version: 5.24.6
- KDE Frameworkds Version: 5.92.0

**Comment by urbanmoon** [comment]
Same problem for about a week. Love this widget and being able to just glance up to see the gorgeous weather I'm missing as I'm stuck here on the computer. lol. I do love it, really. And miss it.

Wunderground 2.4.0
OS: Arch 6.0.6-arch1-1
plasmashell 5.26.2
Qt: 5.15.7
KDE Frameworks: 5.99.0
kf5-config: 1.0

**Comment by kslivings** [comment]
Hopefully you can get the API key updated and get this resolved. I really like this widget.

**Comment by k-donn** [comment]
New API key pushed out here and on KDE pling. Let me know how it's doing. Version 2.5.0

**Comment by kslivings** [comment]
I just got this updated and it seems to be working as before. Thank you and keep up the good work!

**Comment by gldickens3** [comment]
2.5.0 works great!  Thanks!...   Gordon.

**Comment by urbanmoon** [comment]
2.5.0 is working great for me, too! Thank you so much!

**Comment by vmisev** [comment]
2.5.0 is working great, thanks!

**Comment by lucknaumann** [comment]
Oddly, version 2.5.0 isn't working for me. I uninstalled the prior version and reinstalled with the new version. I'm getting the same error.

Wunderground: 2.5.0
OS: KDE neon User 5.26
KDE Plasma Version: 5.26.0
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
kf5-config: 1.0

**Comment by urbanmoon** [comment]
@lucknaumann  I did the same as you and found 2.5.0 to not make a difference. I shut down for the night and was going to deal with it in the morning but lo and behold, when I restarted in the morning, I glanced up and it was working! So didn't need to sort anything out. For whatever reason, the restart solved whatever lingering problem I had.


> Oddly, version 2.5.0 isn't working for me. I uninstalled the prior version and reinstalled with the new version. I'm getting the same error.
> 
> Wunderground: 2.5.0 OS: KDE neon User 5.26 KDE Plasma Version: 5.26.0 KDE Frameworks Version: 5.99.0 Qt Version: 5.15.7 kf5-config: 1.0

**Comment by lucknaumann** [comment]
@urbanmoon I was just thinking that maybe a reboot is what's needed. I'll go ahead and try that, thanks.

**Comment by rqkeating** [comment]
If anyone else stumbles on that issue, I used
 `kquitapp5` plasmashell && kstart5 plasmashell` 
to restart Plasma and that got it working without a reboot.
(Kubuntu 22.10, Plasma 5.26.2 (via backports))

**Comment by k-donn** [comment]
Ok, It does seem Plasma is caching  something part of the widget that doesn't let the update work. But it does seem the update itself works. 

I'll update some instructions on the widget page then mark this closed after a little bit!

**Comment by Scrithy** [comment]
Thanks alot, this worked great. And I appreciate the tip on restarting plasmashell.

**Comment by jimtuttle** [comment]
Tested and working.  Awesome!  I very much appreciate your time and enjoy the widget.  I was just getting ready to ask you if you wanted help porting it to openweathermap but I'm glad that's not necessary and hyper-local weather is great.  

Be well and thanks!
