### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by Alladyn47** [k-donn/plasmoid-wunderground#40]
Good afternoon. Translating to Russian language.
Thanks for the widget.
![Screenshot_20230703_132652](https://github.com/k-donn/plasmoid-wunderground/assets/26250259/223e093e-9698-4fa7-ab83-30589ec0b8c2)
[Russian.zip](https://github.com/k-donn/plasmoid-wunderground/files/11935846/Russian.zip)

**Comment by Alladyn47** [comment]
Fixed typo in settings
[Russian.zip](https://github.com/k-donn/plasmoid-wunderground/files/11935824/Russian.zip)

**Comment by k-donn** [comment]
Спасибо!

Thanks for using the widget! Translations have been added and published to KDE store.
