### ISSUE TITLE
Add/update translation for [LOCALE_CODE eg. de_DE]

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#42]
I worked a bit on the German translation, should be pretty but not entirely complete. You can use it if you want to.
[de_DE.txt](https://github.com/k-donn/plasmoid-wunderground/files/12468648/de_DE.txt)

**Comment by k-donn** [comment]
Thank you for the translations! I will merge this ASAP

**Comment by k-donn** [comment]
Danke schön!
