### ISSUE TITLE
Change color of font used to display temperature

### ISSUE THREAD

**Issue by edwardp3** [k-donn/plasmoid-wunderground#44]
I would like to suggest the color of the font used for the temperature display (currently, yellow) be changed to something more neutral, or provide an option to change the color in the widget, so it can be easily viewed with both KDE light and dark themes. 

Using the light theme, yellow is close to impossible to see. 

Thank you.

![weatherwidget](https://github.com/k-donn/plasmoid-wunderground/assets/73129450/ce9b339f-8f41-48aa-8d17-1bcd26c8a04f)

**Comment by edwardp3** [comment]
Appearance/Global Theme/Colors ands elected a different color scheme, it changed the color to something other than yellow and it's now readable.

**Comment by edwardp3** [comment]
The above didn't work. Upon a reboot, the font color reverted back to yellow.

**Comment by k-donn** [comment]
Hello!

I will add this change this weekend. Currently, the color changes by the value of the temperature.

Adding an option to disable this behavior and use a set color will probably be simplest.

**Comment by k-donn** [comment]
I added a config option "Auto-color temperature" that can be de-selected. When de-selected, the temp text color is the color all the other text is.

Thank you again for helping me improve the widget!

**Comment by edwardp3** [comment]
Thank you for adding the option.
