### ISSUE TITLE
Please add support for KDE Plasma 6

### ISSUE THREAD

**Issue by aenima99x** [k-donn/plasmoid-wunderground#49]
**Is your feature request related to a problem? Please describe.**
Does not run on Plasma6

**Describe the solution you'd like**
Would like widget to run on Plasma6

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by k-donn** [comment]
Got it. 

KDE has released a porting guide so I will begin to go through that (as well as update my own system).

**Comment by k-donn** [comment]
I made a first rough port. It is available for download on KDE Plasma 6 now through the KDE store.

[link](https://www.pling.com/p/2135799/)

Known issues:
The click to configure button does not work. Configuring through the context menu works however.
Icons and icon sizing are messed up.
Compact representation rendering is poor.

**Comment by aidanharris** [comment]
Thanks for taking a look at this.

I was using https://github.com/rliwoch/plasmoid-wunderground-extended but that's broken on Plasma 6 too now https://github.com/rliwoch/plasmoid-wunderground-extended/issues/42

One issue, clicking on the Plasmoid in the panel doesn't seem to do anything right now (it doesn't show a forecast). It does show a forecast if I add it to the desktop.

**Comment by k-donn** [comment]
Got it. A new version is up on the store that fixed some of the panel problems. Plasma 6 has moved a lot of methods around so I am progressing bit by bit.

Next big problem is SVG rendering. Plasma 6 removed the `file` method of `AppletInterface` to find the path of resources in a plasmoid. And I cannot get relative paths to work.

Thank you!

**Comment by edwardp3** [comment]
I am testing OpenMandriva Cooker, with Plasma 6 and the Plasma 6 widget isn't working. When adding, the icon is a green question mark and when selected to edit, a window displays the following:

`Sorry! There was an error loading Wunderground.`

`file:///home/<username-redacted>/.local/share/plasma/plasmoids/com.github.k-donn.plasmoid-wunderground/contents/ui/main.qml:48:30: Invalid property assignment: int expected`
