### ISSUE TITLE
Where are the list of Weatherstatiod ID

### ISSUE THREAD

**Issue by calipomza** [k-donn/plasmoid-wunderground#50]
Where are the list of Weatherstatiod ID. i put "Mendoza" and press TEST STATION or I put "Mendoza" in the look por location and dont show any message

**To Reproduce**
Did you change a setting or did it happen due to some other event?

**Screenshots**
Screenshots are crucial to helping my understand the problem.

**Desktop (output of `plasmashell --version && kf5-config --version`):**
plasmashell 5.27.5
Qt: 5.15.8
KDE Frameworks: 5.103.0
kf5-config: 1.0

**Comment by k-donn** [comment]
Going to [wunderground.com/wundermap](https://www.wunderground.com/wundermap) and making sure "Weather Stations" is selected will show you all of the stations around you. Clicking on one of the icons representing the stations will show you its ID, and that is the ID you need to put into the widget.

For example:
 
<img width="1440" alt="example" src="https://github.com/k-donn/plasmoid-wunderground/assets/58149779/c2efed0b-b813-4cee-9c99-f7eacfd9c970">

Thank you for using my widget!
