### ISSUE TITLE
Add AQI Support

### ISSUE THREAD

**Issue by generallynonsensical** [k-donn/plasmoid-wunderground#51]
**Is your feature request related to a problem? Please describe.**
With the prevalence of wildfires and other air quality contaminants, having the AQI/AQHI listed in the widget would be a great feature for all users. Especially those who are sensitive to AQI/AQHI changes.

**Describe the solution you'd like**
Add the AQI/AQHI to widget.

**Describe alternatives you've considered**
Other widgets but none are even close to this one.

**Additional context**
I am not sure if there are global standards, or if each country has their own measurements. From what I've seen, it's PM2.5 and PM10 that are used.

**Comment by k-donn** [comment]
Thank you so much for using the widget! I will be sure to add this into the KDE 6 version.
