### ISSUE TITLE
Allow translations for the sidepanel of the configuration page

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#54]
Just as the title says, to allow a more complete localization it would be good to make some minor changes to the config.qml.

`import QtQuick
import org.kde.plasma.configuration

ConfigModel {
    ConfigCategory {
        name: i18n("Station")
        icon: "flag"
        source: "config/ConfigStation.qml"
    }
    ConfigCategory {
        name: i18n("Appearance")
        icon: "preferences-desktop-color"
        source: "config/ConfigAppearance.qml"
    }
    ConfigCategory {
        name: i18n("Units")
        icon: "configuration"
        source: "config/ConfigUnits.qml"
    }
    ConfigCategory {
        name: i18n("Debug")
        icon: "preferences-other"
        source: "config/ConfigDebug.qml"
    }
}`

The translation will then appear, after it has been added to the template. Please note I made the translation in the qt5 version and then just copied it to the qt6 version.
![Screenshot_20240328_092907](https://github.com/k-donn/plasmoid-wunderground/assets/62669377/9aea288d-a165-46a8-b391-8a97c9a593da)

**Comment by k-donn** [comment]
Will do. Another simple change I will add is i18n tags to the configure button on the widget.

In addition, I just realized the textual description of conditions in the top right is always set to English. It does not need to be like this because the API can return different language output. It's the same for the forecast.

Keep an eye out for a commit coming.

**Comment by k-donn** [comment]
Version 0.0.7 just added these changes. Let me know if it broke anything.

**Comment by tabascosw** [comment]
Looks good, only the text under the daily forecast has disappeared.
![Screenshot_20240414_093319](https://github.com/k-donn/plasmoid-wunderground/assets/62669377/a0b7425f-e282-474d-bab5-9a4e30560824)

**Comment by tabascosw** [comment]
It is actually worse now, all data in the forecast is gone.

**Comment by k-donn** [comment]
Sorry about that. Line 246 of pws-api.js was improperly copied from above and should be 'night["phrase32_char"]' instead of it being 'day'.

**Comment by tabascosw** [comment]
No problem, after changing the line 246 it works fine. Thanks for your hard work.
![Screenshot_20240414_215824](https://github.com/k-donn/plasmoid-wunderground/assets/62669377/709fb55d-bf4f-4129-b4b8-fa7ff5d96515)
