### ISSUE TITLE
Update version in metadata.json

### ISSUE THREAD

**Issue by DarkXero-dev** [k-donn/plasmoid-wunderground#55]
Hello

Not really a bug, but since I use [**Apdatifier**](https://store.kde.org/p/2135796) in conjuction with this plasmoid, versions don't match KDE store, where it's reported to be version 0.0.6 but in metadata.json says version 2.5.5 (Plasma 5 version) .. Causing Apdatifier to misreport update .. It would be great if versioning is fixed to separate Plasma 5 version from Plasma 6 one.. 

Cheers...

**Comment by k-donn** [comment]
Thanks for catching this! It will be fixed in the next version.

**Comment by DarkXero-dev** [comment]
@k-donn No problem bud, I do my best to help my fellow Linuxers when I can ;)
