### ISSUE TITLE
Add/update translation for [de_DE]

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#56]
Added an update for the German translation based on version 0.1.0. I included the .po and .mo file.
[de_DE.tar.gz](https://github.com/k-donn/plasmoid-wunderground/files/15142817/de_DE.tar.gz)

**Comment by k-donn** [comment]
It's out on the KDE store!

More changes are to come, so I plan on letting all the translators know when the widget is at a good point to add more translations.
