### ISSUE TITLE
Font color not adapted to background

### ISSUE THREAD

**Issue by HaleyACS** [k-donn/plasmoid-wunderground#58]
**Describe the bug**
When using the widget  on dark background, the font color remains black and no text is visible

**To Reproduce**
Install widget and load a black/dark background

**Screenshots**
![image](https://github.com/k-donn/plasmoid-wunderground/assets/12997932/389fd378-c9ca-4696-aa3d-8a7175f0065f)

**Desktop (output of `plasmashell --version && kf5-config --version`):**
Operating System: KDE neon 6.0
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.5.0-35-generic (64-bit)
Graphics Platform: Wayland

**Additional context**
Just the colors that need to be adapted :)

**Comment by k-donn** [comment]
Thank you for using the widget!

I've run into a problem on plasma6 where the text does not adjust to white when the widget first loads. Changing the background to solid then back to transparent has solved your problem in the past. Let me know if that does not work. 

Changing font coloring is in the pipeline for this widget so this is set to be less buggy! Thanks again

**Comment by HaleyACS** [comment]
Hi @k-donn , tried what you suggested, but it didn't work.
I actually have no possibility to change the background to solid then transparent in the configuration settings.
All I can set is "auto-color temperature" - tried that one too.
![image](https://github.com/k-donn/plasmoid-wunderground/assets/12997932/18be97da-4c20-430e-84ac-2cd7077a7b76)

**Comment by HaleyACS** [comment]
Yes - that works. Thanks! Didn't notice it at all :D :+1:
