### ISSUE TITLE
update translation for de_DE

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#59]
Updated translation for de_DE, this includes all your recent changes that have not been published yet. 
[de_DE.tar.gz](https://github.com/user-attachments/files/15567880/de_DE.tar.gz)

**Comment by k-donn** [comment]
Hello! There were even more unreleased changes that were required for the API. I released them now for 0.1.4. It would be better if translations could be made of those!

This version will be most of the front-end changes that need translations. Later planned additions are mostly back end. Thanks again

**Comment by tabascosw** [comment]
Ok, here is the version for 0.1.4.
[de_DE.tar.gz](https://github.com/user-attachments/files/15569244/de_DE.tar.gz)

**Comment by k-donn** [comment]
Awesome! Updated and pushed to KDE store.
