### ISSUE TITLE
Allow users to save multiple locations

### ISSUE THREAD

**Issue by Leonerd-04** [k-donn/plasmoid-wunderground#60]
**Is your feature request related to a problem? Please describe.**
I am a university student, whose university is not in my hometown. What this means is that when I travel between university and home, I have to find the correct station on wunderground every time, which gets tedious, or retrieve my GPS coordinates to let the widget find them, which is also tedious.

**Describe the solution you'd like**
A good solution to the problem is the ability to switch between a few saved stations. In the settings, instead of setting your station, you could add new ones to your saved stations.

To select a station, have the station name in the widget not only display the station name but also be a clickable dropdown menu.

**Describe alternatives you've considered**
One alternative is a "traveling mode", similar to the one featured in https://github.com/rliwoch/plasmoid-wunderground-extended, where it instead just finds the nearest station at all times. I found that to be inaccurate sometimes, when my ISP displays its connection to be far away, such as on a train. I would imagine this wouldn't work with a VPN. Being able to see weather for stations you are not currently near is useful as well, like seeing the forecast the day before moving back to school.

This does have the advantage of having weather information for places you're in only temporarily though.

**Comment by k-donn** [comment]
Thank you for the input! 

The "saved stations" solution sounds promising. I'll get to work on that then.
