### ISSUE TITLE
No weather data when there's no station nearby

### ISSUE THREAD

**Issue by tiamed** [k-donn/plasmoid-wunderground#63]
Example coordinates: 30, 120

**Comment by k-donn** [comment]
Hello! It seems that Wunderground PWS stations have not yet made their way to China. Until then, the searching API returns nothing. 

The long-term plan of the widget is to migrate to [`Plasma Ions`](https://techbase.kde.org/Projects/Plasma/Weather/Ions) to be the weather source. Then, a source that has info for your area can be selected. 

I hope to bring this as soon as possible! Until then, sorry for the inconvenience.
