### ISSUE TITLE
v3.1.0 - Please add the option to delete a station

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#67]
It is nice to add additional stations, but it would be even better to have an option to delete a station from the list, otherwise it will clutter over time.
Also the button "choose" from that section can not be translated.

**Comment by k-donn** [comment]
Thanks for the input! There's a lot of simplification and refactoring to do with the station picking and adding a "remove" option is on the TODO.

As for the translations, the intention was that button was going to be provided by the default weather widget but it seems that feature is not working. Updates to come.

**Comment by k-donn** [comment]
Closed in 3.1.2!
