### ISSUE TITLE
Incorrect units used in metric settings

### ISSUE THREAD

**Issue by HairyMcLeary** [k-donn/plasmoid-wunderground#7]
Hi, Great app, just one problem: When using metric settings it reports rainfall as cm/hr, the correct unit of measurement should be mm/hr. If you go to the Wunderground web page for the nearest station it reports rainfall as mm/hr whilst your app reports cm/hr for the same station.

**Comment by k-donn** [comment]
Thanks for the input. I will add the correct unit of `mm`. 
According to the [Wunderground Usage Guide](https://docs.google.com/document/d/13HTLgJDpsb39deFzk_YCQ5GoGoZCO_cRYzIxbwvgJLI/edit) `mm` should be used for rain accumulation and `cm` for snow accumulation. I was being lazy and just used `cm` for both.
