### ISSUE TITLE
Custom icons no longer work in forecast view

### ISSUE THREAD

**Issue by tabascosw** [k-donn/plasmoid-wunderground#73]
When I use the custom icons, they no longer work correctly in the forecast view. They stay the same throughout the forecast period. In the attached pictures you can see the difference from the system icon.
![Bildschirmfoto_20240902_150432](https://github.com/user-attachments/assets/b3940cb3-14d2-454f-843e-96b5c4d6c453)

![Bildschirmfoto_20240902_150321](https://github.com/user-attachments/assets/f86600cf-9c7e-48ce-b203-5788b8dd0468)

**Comment by k-donn** [comment]
Ah got it, the weather forecast was so similar for me that I didn't notice this. I'll fix this.

**Comment by tabascosw** [comment]
Still not fixed:
![Bildschirmfoto_20240902_205657](https://github.com/user-attachments/assets/cda2613f-1c80-423f-8a06-e7dbfe628efa)
![Bildschirmfoto_20240902_205742](https://github.com/user-attachments/assets/dfec9dd7-432b-4a1e-a766-c440853d5967)

**Comment by tabascosw** [comment]
It works now and here is the latest German translation.
[de_DE.zip](https://github.com/user-attachments/files/16840766/de_DE.zip)
