### ISSUE TITLE
Looks like the icon is off center in the system tray

### ISSUE THREAD

**Issue by Elec3137** [k-donn/plasmoid-wunderground#75]
The icon appear very off center.

This was the case upon plasmoid installation, and does not change using the system icons option

![image](https://github.com/user-attachments/assets/087b76b9-8db4-4180-ba59-41bebc1f59cb)
![image](https://github.com/user-attachments/assets/20a28ce2-1cd4-4bf2-a9d7-763f317c6785)

plasmashell 6.1.5
Latest packages on eOS
Using [sweet-ambar-blue KDE and kvantum theme](https://store.kde.org/p/2157756)
Superficially switching to breeze-dark doesn't seem to change anything, however I am still suspicious there's something wrong with the theme (partially since plasmashell segfaults if I try to drag a widget with sweet-ambar-blue theme)

Screen is not scaled, changing scaling has no effect

**Comment by k-donn** [comment]
Hello, thanks for using my widget and putting up with the delay!

@Elec3137 Is this in the system tray? If it is, then the problem is likely with how the widget hides the temperature in the system tray.

If this is not in the system tray, I will look through other parts of the widget to see if something else is wrong with the font/icon calculation.

I will work on replicating the issue as well!

**Comment by Elec3137** [comment]
Yes, it is in the system tray as mentioned in the title of the Issue.
Thanks for responding!

**Comment by k-donn** [comment]
Oh my goodness, the title flew right over my head. Sorry about that.

The issue is probably with how the widget calculates its size based on the temperature text and icon. More calculations will need to be done for this case. I'll work on testing some new rendering logic.

**Comment by k-donn** [comment]
@Elec3137 3.2.3 has new logic for calculating sizes based on showing and not showing temperature. See if that works!

**Comment by tabascosw** [comment]
The changes create other problems, you can no longer change the font and size of the text in the control panel, it doesn't react to any changes. Spacing looks also off, it takes up a lot more space than before.  Top shows new version, bottom the old version. I did not have any issues with the spacing and alignment in the old version. 
![Bildschirmfoto_20241007_084731](https://github.com/user-attachments/assets/4b0c605a-f3bc-4d81-84e4-1917c703db9d)

**Comment by k-donn** [comment]
The font size/styling breaking was expected. I was planning on implementing it once the original alignment issue was corrected. Now, I can hook up the control panel to the text and adjust/make the spacing customizable!

Thanks!

**Comment by k-donn** [comment]
I temporarily removed the font customization settings. I will replace it with the QtQuick FontDialog. Also, the extra spacing on the right should now be removed.

**Comment by tabascosw** [comment]
Thanks, spacing is now ok.
