### ISSUE TITLE
Station config panel is blank

### ISSUE THREAD

**Issue by babelfish** [k-donn/plasmoid-wunderground#76]
**Describe the bug**
When opening the config dialog, the station panel is blank. The other panels all work. If I click on another panel and then try to switch to the Station one, it leaves the previous panel open while highlighting the Station button on the sidebar (see second screenshot).

**To Reproduce**
It's been like this since I installed it.

**Screenshots**
![image](https://github.com/user-attachments/assets/f5ca99d2-18aa-44c3-8d6f-e2e3a461c313)
![image](https://github.com/user-attachments/assets/5c717799-9b24-4daa-86a1-eb10c95545c5)

**Desktop (output of `plasmashell --version):**
plasmashell 6.1.5

**Additional context**
version 3.2.3

**Comment by k-donn** [comment]
Yikes! I pushed out some changes to fix a different part of the widget, but I did not expect this to happen. More changes are coming soon to fix this.

**Comment by k-donn** [comment]
Some settings were temporarily removed. Hopefully that fixes it.

**Comment by k-donn** [comment]
Yes, those are the settings. Sorry about the inconvenience, new changes are coming within the week.

**Comment by k-donn** [comment]
@Kandelai @babelfish 3.2.5 is out with the font dialog added back in. I wasn't able to implement underline/bold/strike-through quite yet, so those will come soon.

But, let me know how it is working!

**Comment by Kandelai** [comment]
@k-donn 3.2.5 works great, able to change the font/size in system tray, perfect. Thank you!

**Comment by babelfish** [comment]
The station config panel still isn't working for me in 3.2.5.

**Comment by babelfish** [comment]
And actually the Appearance panel now doesn't display either.

**Comment by babelfish** [comment]
Hm, I restarted my computer this morning and now those panels display properly.
