### ISSUE TITLE
strange icon effect (papirus)

### ISSUE THREAD

**Issue by g1bber1sh** [k-donn/plasmoid-wunderground#80]
hello

with system icons theme enabled in the settings, AND the system icon theme is papirus, some strange things happen on the forecast page. best way to explain is a picture https://imgur.com/a/yA9v32b
see the cloudy icons

it can probably be reproduced by applying the papirus theme (provided theres a cloudy icon in the forecast page, seems to only affect those)

this is version 3.3.0 but i think it happened in a previous version as well, not sure when it started because i think i skipped a version or 2. it did not happen back when your plasmoid was only using system icons

plasmashell 6.1.5

it does not happen with the breeze icon theme, or the built in theme

**Comment by k-donn** [comment]
Hello, thanks for opening the issue!

I have replicated the issue and noticed the problem. Paprius does not have all weather symbolic icons provided. The offending icons in your example are `weather-clouds(-symbolic)` and  `weather-many-clouds(-symbolic)`. Paprius does not have the `(-symbolic)` versions of these icons.

Paprius does have the symbolic version of `weather-few-clouds-symbolic` and it displays themed for the 12th day in your picture. This widget's rendering logic currently treats all icons as though they're set up to be themed and attempts to apply the theme. That is causing the blocked out icon rendering for the other icons.

I will add an option not to apply the system color scheme to icons. When you choose that, it will render the icons with their predefined colors and should render properly.

If you want the symbolic look of the icons still, then Papirus will need to add the symbolic icons. It looks like there has been some [discussion](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3595) within Papirus about this needing to be done. There is a guide [here](https://develop.kde.org/docs/plasma/theme/theme-colors/) on how to edit existing SVGs to add color scheme support.

The change to add the system theming option will come soon. Thank you for your interest again!

**Comment by g1bber1sh** [comment]
hi
thank you for the thorough answer and links! 
now that i think about it those icons never really worked even in the past, they were displayed as coloured icons instead (not symbolic) - so when i said above that it worked in the past that was wrong, i just didnt remember.

i have found a solution however that works for me, even if its not ideal. in ForecastItem.qml i changed 
readonly property int preferredIconSize: Kirigami.Units.iconSizes.large
to
readonly property int preferredIconSize: Kirigami.Units.iconSizes.medium

that does the job for me, perhaps it can be included as an option in the settings for the time being. in any case that solves it for me id say, doesent look half bad

**Comment by g1bber1sh** [comment]
hi
thank you for the thorough answer and links! 
now that i think about it those icons never really worked even in the past, they were displayed as coloured icons instead (not symbolic) - so when i said above that it worked in the past that was wrong, i just didnt remember.

i have found a solution however that works for me, even if its not ideal. in ForecastItem.qml i changed 
readonly property int preferredIconSize: Kirigami.Units.iconSizes.large
to
readonly property int preferredIconSize: Kirigami.Units.iconSizes.medium

that does the job for me, perhaps it can be included as an option in the settings for the time being. in any case that solves it for me id say, doesent look half bad

edit:oh and in TopPanel.qml as well

**Comment by k-donn** [comment]
Now that I look closer, the symbolic icons just are not packaged for the larger sizes. For 32x32 and below there are symbolic icons available. Interesting, I will add the icon size customization as well. 
![ManyClouds](https://github.com/user-attachments/assets/706ab5dc-e69e-4753-81b9-4dcc4a853bb0)

**Comment by k-donn** [comment]
![Settings](https://github.com/user-attachments/assets/27c94abf-7316-4758-abf9-8fd6c56ccb91)
![NewBehavior](https://github.com/user-attachments/assets/ef346f10-d30e-40ed-ac04-61124e6bba81)

The size changing option seems like it's working.

**Comment by g1bber1sh** [comment]
looks proper good! thanks for your work
could maybe do with a bit of padding around the icon in the top left corner, at least with the default breeze theme, its right up against the edges here, but that is a very minor thing.
thanks again
PS i envy your temperatures

**Comment by k-donn** [comment]
I added an option to customize the amount of padding around that icon! A further goal of the widget is to generally add more features like that so stay tuned!

I am going to commit these changes and put out a new version. Thanks again!
