### ISSUE TITLE
Brazilian Portuguese translation (pt_BR)

### ISSUE THREAD

**Issue by jpmadeira** [k-donn/plasmoid-wunderground#84]
[portugues_brasil.txt](https://github.com/user-attachments/files/17707748/portugues_brasil.txt)

**Comment by k-donn** [comment]
Thank you so much for the translations!

Right after you provided them, I finally pushed some changes that added more entries. If you could please copy and translate the new entries in the [`pt_BR.po`](https://github.com/k-donn/plasmoid-wunderground/blob/main/plasmoid/translate/pt_BR.po) file, that would be awesome!
