### ISSUE TITLE
Adjust the polling schedule

### ISSUE THREAD

**Issue by tateeskew** [k-donn/plasmoid-wunderground#9]
This is a feature request.
It would be great to be able to adjust the polling schedule for the widget. Right now it polls every 10 seconds and dumps lines in the system log every 10 seconds. It would be really great to be able to have a configuration setting for the polling interval.

**Comment by k-donn** [comment]
Thanks for bearing with me, been busy. I have been meaning to control the console logging for a while so I will add that. I will also add an option to change the refresh rate.
